import stylistic from "@stylistic/eslint-plugin";
import jsdoc from "eslint-plugin-jsdoc";
import globals from "globals";

export default [
  { ignores: ["dnd5e-compiled*", "dist/", "packs/"] },
  {
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.node,
        ...globals.jquery
      },
      sourceType: "module"
    },
    plugins: { jsdoc, "@stylistic": stylistic },
    rules: {
      "@stylistic/array-bracket-spacing": ["warn", "never"],
      "array-callback-return": "warn",
      "@stylistic/arrow-spacing": "warn",
      "@stylistic/comma-dangle": ["warn", "never"],
      "@stylistic/comma-style": "warn",
      "@stylistic/computed-property-spacing": "warn",
      "constructor-super": "error",
      "default-param-last": "warn",
      "@stylistic/dot-location": ["warn", "property"],
      "@stylistic/eol-last": ["error", "always"],
      eqeqeq: ["warn", "smart"],
      "@stylistic/function-call-spacing": "warn",
      "func-names": ["warn", "never"],
      "getter-return": ["warn", { allowImplicit: true }],
      "@stylistic/lines-between-class-members": "warn",
      "@stylistic/new-parens": ["warn", "always"],
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "error",
      "no-constant-condition": "warn",
      "no-constructor-return": "warn",
      "no-delete-var": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-duplicate-imports": ["warn", { includeExports: true }],
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-implicit-coercion": ["warn", { allow: ["!!"] }],
      "no-implied-eval": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-iterator": "warn",
      "no-lone-blocks": "warn",
      "no-lonely-if": "warn",
      "no-misleading-character-class": "warn",
      "@stylistic/no-mixed-operators": "warn",
      "no-multi-str": "warn",
      "@stylistic/no-multiple-empty-lines": "warn",
      "no-new-func": "warn",
      "no-object-constructor": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-new-wrappers": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-proto": "warn",
      "no-regex-spaces": "warn",
      "no-script-url": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-setter-return": "warn",
      "no-sequences": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "error",
      "no-unexpected-multiline": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unneeded-ternary": "warn",
      "no-unreachable": "warn",
      "no-unreachable-loop": "warn",
      "no-unsafe-negation": ["warn", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": ["warn", { disallowArithmeticOperators: true }],
      "no-unused-expressions": "warn",
      "no-useless-backreference": "warn",
      "no-useless-call": "warn",
      "no-useless-catch": "warn",
      "no-useless-computed-key": ["warn", { enforceForClassMembers: true }],
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-rename": "warn",
      "no-useless-return": "warn",
      "no-var": "warn",
      "no-void": ["warn", { allowAsStatement: true }],
      "@stylistic/no-whitespace-before-property": "warn",
      "prefer-numeric-literals": "warn",
      "prefer-object-spread": "warn",
      "prefer-regex-literals": "warn",
      "prefer-spread": "warn",
      "@stylistic/rest-spread-spacing": ["warn", "never"],
      "@stylistic/semi-spacing": "warn",
      "@stylistic/semi-style": ["warn", "last"],
      "@stylistic/space-unary-ops": ["warn", { words: true, nonwords: false }],
      "@stylistic/switch-colon-spacing": "warn",
      "symbol-description": "warn",
      "@stylistic/template-curly-spacing": ["warn", "never"],
      "unicode-bom": ["warn", "never"],
      "use-isnan": ["warn", { enforceForSwitchCase: true, enforceForIndexOf: true }],
      "valid-typeof": ["warn", { requireStringLiterals: true }],
      "@stylistic/wrap-iife": ["warn", "inside"],

      "@stylistic/arrow-parens": ["warn", "as-needed", { requireForBlockBody: false }],
      "capitalized-comments": ["warn", "always", { ignoreConsecutiveComments: true }],
      "@stylistic/comma-spacing": "warn",
      "dot-notation": "warn",
      "@stylistic/indent": ["warn", 2, { SwitchCase: 1 }],
      "@stylistic/key-spacing": "warn",
      "@stylistic/keyword-spacing": ["warn", { overrides: { catch: { before: true, after: false } } }],
      "@stylistic/max-len": ["warn", {
        code: 120,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true
      }],
      "no-extra-boolean-cast": ["warn", { enforceForLogicalOperands: true }],
      "@stylistic/no-extra-semi": "warn",
      "@stylistic/no-multi-spaces": ["warn", { ignoreEOLComments: true }],
      "@stylistic/no-tabs": "warn",
      "no-throw-literal": "error",
      "@stylistic/no-trailing-spaces": "warn",
      "no-useless-escape": "warn",
      "no-unused-vars": ["warn", { args: "none" }],
      "@stylistic/nonblock-statement-body-position": ["warn", "beside"],
      "one-var": ["warn", "never"],
      "@stylistic/operator-linebreak": ["warn", "before", {
        overrides: { "=": "after", "+=": "after", "-=": "after" }
      }],
      "prefer-template": "warn",
      "@stylistic/quote-props": ["warn", "as-needed", { keywords: false }],
      "@stylistic/quotes": ["warn", "double", { avoidEscape: true, allowTemplateLiterals: false }],
      "@stylistic/semi": "warn",
      "@stylistic/space-before-blocks": ["warn", "always"],
      "@stylistic/space-before-function-paren": ["warn", {
        anonymous: "never",
        named: "never",
        asyncArrow: "always"
      }],
      "@stylistic/spaced-comment": "warn",

      "jsdoc/check-access": "warn",
      "jsdoc/check-alignment": "warn",
      "jsdoc/check-examples": "off",
      "jsdoc/check-indentation": "off",
      "jsdoc/check-line-alignment": "off",
      "jsdoc/check-param-names": "warn",
      "jsdoc/check-property-names": "warn",
      "jsdoc/check-syntax": "off",
      "jsdoc/check-tag-names": ["warn", { definedTags: ["import"] }],
      "jsdoc/check-types": "warn",
      "jsdoc/check-values": "warn",
      "jsdoc/empty-tags": "warn",
      "jsdoc/implements-on-classes": "warn",
      "jsdoc/match-description": "off",
      "jsdoc/newline-after-description": "off",
      "jsdoc/no-bad-blocks": "warn",
      "jsdoc/no-defaults": "off",
      "jsdoc/no-types": "off",
      "jsdoc/no-undefined-types": "off",
      "jsdoc/require-description": ["warn", { checkConstructors: false }],
      "jsdoc/require-description-complete-sentence": "off",
      "jsdoc/require-example": "off",
      "jsdoc/require-file-overview": "off",
      "jsdoc/require-hyphen-before-param-description": ["warn", "never"],
      "jsdoc/require-jsdoc": "warn",
      "jsdoc/require-param": "warn",
      "jsdoc/require-param-description": "off",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-param-type": "warn",
      "jsdoc/require-property": "warn",
      "jsdoc/require-property-description": "off",
      "jsdoc/require-property-name": "warn",
      "jsdoc/require-property-type": "warn",
      "jsdoc/require-returns": "warn",
      "jsdoc/require-returns-check": "warn",
      "jsdoc/require-returns-description": "off",
      "jsdoc/require-returns-type": "warn",
      "jsdoc/require-throws": "off",
      "jsdoc/require-yields": "warn",
      "jsdoc/require-yields-check": "warn",
      "jsdoc/valid-types": "off"
    },
    settings: {
      jsdoc: {
        mode: "typescript",
        preferredTypes: {
          ".<>": "<>",
          Object: "object"
        },
        tagNamePreference: {
          auguments: "extends"
        }
      }
    }
  }
];
