_id: mmTraining000000
name: Training
type: feat
system:
  type:
    value: monster
    subtype: ''
  activities: {}
  uses:
    spent: 0
    recovery: []
    max: ''
  description:
    value: >-
      <p class="feature">The [[lookup @name lowercase]] has proficiency in one
      skill of the DM's choice and has Advantage whenever it makes an ability
      check using that skill.</p>
    chat: ''
  identifier: training
  source:
    revision: 1
    rules: '2024'
  enchant: {}
  prerequisites:
    level: null
  properties:
    - trait
  requirements: ''
folder: L9Zgr8qAPc3ngKhb
img: icons/magic/control/buff-strength-muscle-damage-red.webp
effects: []
flags: {}
_stats:
  duplicateSource: null
  coreVersion: '13.346'
  systemId: dnd5e
  systemVersion: 4.2.0
  createdTime: 1733432292956
  modifiedTime: 1736182535843
  lastModifiedBy: dnd5ebuilder0000
  exportSource: null
sort: 13100000
ownership:
  default: 0
_key: '!items!mmTraining000000'
